spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: "jdbc:mysql://localhost:3306/moviedb"
    username: dbuser
    password: pwd123
  liquibase:
    enabled: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  port: 8080



